In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
dataset=pd.read_csv('data/Social_Network_Ads.csv')

In [29]:
X = dataset.iloc[:, [1,2, 3]].values
y = dataset.iloc[:, 4].values

In [30]:
X

array([['Male', 19, 19000],
       ['Male', 35, 20000],
       ['Female', 26, 43000],
       ...,
       ['Female', 50, 20000],
       ['Male', 36, 33000],
       ['Female', 49, 36000]], dtype=object)

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [32]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [33]:
label=LabelEncoder()

In [34]:
X[:,0]=label.fit_transform(X[:,0])

In [35]:
X[:4,:]

array([[1, 19, 19000],
       [1, 35, 20000],
       [0, 26, 43000],
       [0, 27, 57000]], dtype=object)

In [36]:
state_onehot_encoder = OneHotEncoder(categorical_features = [0], dtype = np.int)
X = state_onehot_encoder.fit_transform(X).toarray()

In [37]:
X[:4,:]

array([[0.0e+00, 1.0e+00, 1.9e+01, 1.9e+04],
       [0.0e+00, 1.0e+00, 3.5e+01, 2.0e+04],
       [1.0e+00, 0.0e+00, 2.6e+01, 4.3e+04],
       [1.0e+00, 0.0e+00, 2.7e+01, 5.7e+04]])

In [38]:
from sklearn.cross_validation import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [40]:
X_train[:5, :]

array([[0.00e+00, 1.00e+00, 5.80e+01, 1.44e+05],
       [1.00e+00, 0.00e+00, 5.90e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 2.40e+01, 5.50e+04],
       [1.00e+00, 0.00e+00, 2.60e+01, 3.50e+04],
       [1.00e+00, 0.00e+00, 5.80e+01, 3.80e+04]])

In [41]:
y_train[:5]

array([1, 0, 0, 0, 1])

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
sc=StandardScaler()

In [44]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
X_train[:5, :]

array([[-1.02532046,  1.02532046,  1.92295008,  2.14601566],
       [ 0.97530483, -0.97530483,  2.02016082,  0.3787193 ],
       [ 0.97530483, -0.97530483, -1.3822153 , -0.4324987 ],
       [ 0.97530483, -0.97530483, -1.18779381, -1.01194013],
       [ 0.97530483, -0.97530483,  1.92295008, -0.92502392]])

In [46]:
y_train[:5]

array([1, 0, 0, 0, 1])

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [68]:
knn=KNeighborsClassifier(n_neighbors=11)

In [69]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=11, p=2,
           weights='uniform')

In [70]:
# Predicting the Test set results
y_test_pred = knn.predict(X_test)

In [71]:
knn.score(X_train,y_train)

0.90625

In [72]:
knn.score(X_test,y_test)

0.95